import { chromium } from 'playwright'
const browser = await chromium.launch({ headless: true })
const page = await browser.newPage({ viewport: { width: 1440, height: 900 } })
await page.goto('http://127.0.0.1:5173/', { waitUntil: 'networkidle' })
await page.waitForTimeout(800)
await page.screenshot({ path: '/opt/cursor/artifacts/screenshots/white_orange_hero.png' })
await page.getByRole('button', { name: 'Get app' }).first().click()
await page.getByRole('dialog').waitFor()
await page.waitForTimeout(300)
await page.screenshot({ path: '/opt/cursor/artifacts/screenshots/white_orange_waitlist.png' })
await page.getByRole('button', { name: 'Close' }).click()
await page.locator('#get-started').scrollIntoViewIfNeeded()
await page.waitForTimeout(400)
await page.screenshot({ path: '/opt/cursor/artifacts/screenshots/white_orange_closing.png' })
await browser.close()
console.log('ok')
